version: '3'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: 
      - ./api:/var/www/html
      - ./api/apache2.conf:/etc/apache2/apache2.conf
    stdin_open: true
    tty: true
    ports:
      - 8000:80
    environment:
      - MYSQLHOST=db
    networks:
      - mynetwork
  db:
    container_name: mysql-database
    image: mysql
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./api/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge